spring:
  datasource:
    url: jdbc:h2:tcp://localhost//Users/leekyoungchang/Desktop/Study/computer/db/h2Database/querydslDB
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug